### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by quazar-omega** [sgryjp/vscode-stable-sort#12]
Could you publish this extension on [Open VSX](https://open-vsx.org/about) so that OSS builds of VSCode (like VSCodium) can install and update it easily?

**Comment by sgryjp** [comment]
Hi. Thank you for letting me know about Open VSX. I’ll take a look into the project when I could make some free time.

**Comment by quazar-omega** [comment]
That's great, thanks for taking this into consideration!

**Comment by sgryjp** [comment]
Now Smart Sort is [published on OpenVSX](https://open-vsx.org/extension/sgryjp/vscode-stable-sort).
