### ISSUE TITLE
Sort within parentheses

### ISSUE THREAD

**Issue by carlosmgilp** [sgryjp/vscode-stable-sort#7]
Hello Brother how are you.
I use the AutoCAD AutoLISP Extension programming code
VSCode 1.55.2
Windowns 10

I want to ask you if you could add an option to order all the words that are inside parentheses.
Regardless of whether they are on different lines.

Example 1:

I select what is inside the parentheses.

![image](https://user-images.githubusercontent.com/80189444/117065876-01610580-acf6-11eb-9f30-324f9eaf647e.png)

And he gave me everything neat and a single space between words.
It must be taken into account that the slash must be next to the opening parenthesis.

![image](https://user-images.githubusercontent.com/80189444/117066002-30777700-acf6-11eb-9474-8eee011bc294.png)

Example 2:

In this case the slash is intermediate.

![image](https://user-images.githubusercontent.com/80189444/117067554-2d7d8600-acf8-11eb-97e0-25a0b6eb0c5b.png)

In this case you should only order what is on the right side of the slash.

![image](https://user-images.githubusercontent.com/80189444/117068314-2014cb80-acf9-11eb-8f78-2d015dc2cb29.png)

If you could give that option I would appreciate it.
It could be an option in the settings.

Thanks.

**Comment by sgryjp** [comment]
Hi @carlosmgilp,

Hmm... as far as I understand, what you requested requires the extension to recognize Lisp (or AutoLISP?) syntax. Currently such "language aware" sorting is out of the extension's scope. So, I'm sorry to write this but I will not add the feature.

**Comment by carlosmgilp** [comment]
Ok brother.
Thanks.
